# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoappweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoappweb
  template:
    metadata:
      labels:
        app: todoappweb
    spec:
      containers:
        - name: todoapp
          image: louaykharouf/todoapp-web
          ports:
            - containerPort: 8000
          env:
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: todoappdb-svc
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: todoapp
            - name: DB_USERNAME
              valueFrom: 
                       secretKeyRef: 
                             name: db-secret
                             key: username
            - name: DB_PASSWORD
              valueFrom: 
                       secretKeyRef: 
                             name: db-secret
                             key: password
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: todoapp-service
spec:
  selector:
    app: todoappweb
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001