# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoappdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoappdb
  template:
    metadata:
      labels:
        app: todoappdb
    spec:
      containers:
        - name: db
          image: mysql:8
          env:
            - name: MYSQL_DATABASE
              value: todoapp
            - name: MYSQL_USER
              valueFrom: 
                        secretKeyRef: 
                          name: db-secret
                          key: username
              
            - name: MYSQL_PASSWORD
              valueFrom: 
                        secretKeyRef: 
                            name: db-secret
                            key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: 
                        secretKeyRef: 
                            name: db-secret
                            key: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim

---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: todoappdb-svc
spec:
  selector:
    app: todoappdb
  type: NodePort
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306